export const insults = [
  "You have the charisma of a dial tone.",
  "You're like a cloud — when you disappear, it's a beautiful day.",
  "You're proof that even evolution takes a break sometimes.",
  "You're not stupid; you just have bad luck thinking.",
  "You bring everyone so much joy when you leave the room.",
  "You’re like a software update — always inconvenient and rarely useful.",
  "Your secrets are safe with me. I never listen anyway.",
  "You could be replaced by a rubber duck and nobody would notice.",
  "You’re like a Wi-Fi signal — weak and easily lost.",
  "Your gene pool needs a lifeguard.",
  "You have the grace of a falling vending machine.",
  "You're as useless as the 'g' in lasagna.",
  "You’re living proof that autocorrect can’t fix everything.",
  "You have the emotional range of a teaspoon.",
  "You're like a cloud storage error — confusing and unnecessary.",
  "You could trip over a wireless connection.",
  "You’re the human equivalent of an expired coupon.",
  "Your personality is like a dial-up modem — loud and outdated.",
  "You’re not the dumbest person alive, but you better hope they don’t die.",
  "You bring so much peace… mostly because you’re silent when you’re not here.",
  "You could make onions cry.",
  "You're like a math problem — I don’t like you, and I don’t get you.",
  "You have a face for radio and a voice for print.",
  "Your aura screams ‘buffering.’",
  "You’re like a cloud — fluffy, aimless, and blocking the sun.",
  "You’re as sharp as a marble.",
  "You could hide behind a Wi-Fi signal and still get lost.",
  "You’re like a low battery warning — annoying and impossible to ignore.",
  "You have the self-awareness of a potato.",
  "You're like a participation trophy with opinions.",
  "You're the human version of pop-up ads.",
  "You're as useful as a screen door on a submarine.",
  "You’re the reason the gene pool needs a fence.",
  "You’re about as intimidating as a loaf of bread.",
  "You’re like a broken pencil — pointless.",
  "You remind me of a cloud of mosquitoes: loud, irritating, and impossible to escape.",
  "You're not the sharpest knife in the drawer — more like a spoon.",
  "You’re like a software bug that no one wants to fix.",
  "You could start an argument in an empty room.",
  "You have the memory of a goldfish and the confidence of a pigeon.",
  "You’re the human version of a loading screen.",
  "You bring chaos wherever you go — and not the fun kind.",
  "You’re about as deep as a puddle in the desert.",
  "You make traffic jams seem peaceful.",
  "You’re like a fire drill that never ends.",
  "You’re as confusing as double negatives in English class.",
  "You’re like glitter — impossible to get rid of and mostly unnecessary.",
  "You could make a happy meal depressed.",
  "You're like decaf coffee — disappointing and pointless.",
  "You have the presence of a background app.",
];

export const compliments = [
  "You make 'effortless' look like an art form.",
  "You could probably convince Wi-Fi to connect faster just by smiling at it.",
  "You’re like a human plot twist—in the best way.",
  "How are you both cool and warm at the same time?",
  "You have main character energy, and the soundtrack agrees.",
  "You make people forget what they were just complaining about.",
  "You’re the reason 'wow' was invented.",
  "You look like you smell like good decisions and expensive candles.",
  "If charisma were a currency, you’d cause inflation.",
  "You make reality look Photoshopped.",
  "You could walk into a hurricane and your hair would still look good.",
  "Your mirror must feel honored every morning.",
  "You look like a filter Instagram wishes it had.",
  "You’re dangerously close to being a Greek myth.",
  "Even your shadow looks elegant.",
  "If 'glow' were a setting, you’d be on max.",
  "You look like you smell like sunshine and good news.",
  "The camera doesn’t do you justice—it’s intimidated.",
  "You’re proof that good lighting exists naturally.",
  "Are you a limited edition or what?",
  "You make confidence look effortless.",
  "You could make small talk sound like a TED Talk.",
  "You have the kind of presence people remember for no clear reason.",
  "Your sense of humor could heal nations.",
  "You make doing nothing look productive.",
  "You’re the calm in everyone else’s chaos.",
  "You have the kind of timing comedians dream about.",
  "You could probably outshine the moon on a good night.",
  "You make other people feel like they’re in on the joke.",
  "You could make a motivational poster jealous.",
  "If looks could kill, you’d still be polite about it.",
  "You’re like a good plot twist—unexpected and completely captivating.",
  "You could make 'just existing' look like a performance.",
  "You’ve got that 'can’t put my finger on it but wow' kind of charm.",
  "I’m starting to think gravity works harder around you.",
  "You look like you belong in someone’s favorite memory.",
  "You’d win 'best person to get lost with.'",
  "You look like the good part of someone’s day.",
  "You make smiling contagious—in a good way.",
  "You could make a paper bag look fashionable.",
  "You make everyone’s day about 12% better.",
  "You’re the human version of a good mood.",
  "You make kindness look cool.",
  "You’re like a walking serotonin boost.",
  "You somehow manage to be comforting and interesting.",
  "You give off the kind of calm people pay therapists for.",
  "You’re the kind of person playlists are made for.",
  "You have great taste—especially in existing.",
  "You make 'just being here' feel like an event.",
  "The world seems to have better lighting when you’re around.",
];

export const conversationBombshells = [
  "It’s not about being right, it’s about being remembered.",
  "Everyone talks about balance, but nobody asks who built the scales.",
  "The real problem is that everyone thinks they’re the exception.",
  "It’s funny how everyone wants progress, until it shows up uninvited.",
  "The answer’s obvious, it’s just hiding behind the wrong question.",
  "You can’t call it chaos if you understand the pattern.",
  "That’s the thing about truth — it’s never in a hurry.",
  "It’s amazing how predictable originality has become.",
  "Every solution eventually becomes someone else’s problem.",
  "That’s why I stopped explaining and started observing.",
  "The loudest opinions usually come from the quietest rooms.",
  "Everything makes sense once you stop needing it to.",
  "That’s what happens when confidence outruns understanding.",
  "If it were easy to see, it wouldn’t be worth noticing.",
  "Everyone wants transparency until they’re the ones being seen through.",
  "You don’t need to win the argument if you’ve already won the perspective.",
  "Simplicity looks complicated to people addicted to confusion.",
  "That’s why information isn’t the same thing as insight.",
  "You can’t innovate if you’re still trying to fit in.",
  "That’s not a paradox — it’s just poor observation.",
  "Everyone wants clarity, but nobody reads the fine print.",
  "That’s not luck — that’s timing disguised as humility.",
  "If you need a reason, you’ve already missed the point.",
  "That’s what happens when logic tries to explain emotion.",
  "Everyone claims to think differently — they just think the same differently.",
  "You don’t lose perspective, you just outgrow it.",
  "That’s why simplicity scares people — it leaves them nothing to hide behind.",
  "The system isn’t broken; it’s just optimized for the wrong goal.",
  "You can’t learn much when you’re busy defending what you know.",
  "It’s not deep — it’s just accurate.",
  "That’s what happens when the map starts believing it’s the territory.",
  "You can’t be ahead of your time if you’re still checking the clock.",
  "People always underestimate how obvious the future looks in hindsight.",
  "That’s not overthinking — that’s just thinking longer than most people can stand.",
  "Everything makes sense — it’s just not your turn to understand yet.",
  "You can’t see the pattern if you’re part of it.",
  "The more certain someone sounds, the less they’ve thought about it.",
  "You can’t break a system that profits from the breaking.",
  "People don’t fear change — they fear being changed.",
  "Every shortcut has an unadvertised cost.",
  "Sometimes the only proof you get is hindsight.",
  "The longer you look for meaning, the more you miss it.",
  "Everyone wants the truth until it disagrees with them.",
  "The future always looks ridiculous until it arrives.",
  "People confuse confidence for competence.",
  "Every generation thinks it invented self-awareness.",
  "You can’t disrupt something you don’t understand.",
  "People say ‘it is what it is’ when they’ve run out of vocabulary.",
  "The opposite of chaos isn’t order — it’s boredom.",
  "If you need validation, it’s not a belief — it’s marketing.",
  "We call it luck because we don’t want to admit it’s timing.",
  "Everyone wants honesty, just not directed at them.",
  "Complex problems rarely have simple people.",
  "You can’t lead if you still need to be liked.",
  "Every opinion sounds smart in an echo chamber.",
  "You can’t claim to think freely while chasing approval.",
  "Sometimes clarity looks like arrogance to the confused.",
  "The truth is usually impolite.",
  "You don’t learn from mistakes — you learn from noticing them.",
  "You can’t reinvent the wheel if you’re scared to leave the road.",
  "Most people don’t want the truth — they want reassurance with better branding.",
  "The loudest voice usually belongs to the least certain person.",
  "You don’t find balance; you build it and break it daily.",
  "That’s not intuition — it’s pattern recognition with good timing.",
  "Most people defend their comfort, not their principles.",
  "You can’t reason with someone who’s protecting their illusion.",
  "If everything’s a priority, nothing actually is.",
  "People call it luck when they don’t want to admit it was effort.",
];
